"""Generate every current scientific table/number from immutable result exports."""
from common import *
import re,shutil
P=ROOT/'papers/interaction_recoverability_iclr2027/v6';T=P/'tables';T.mkdir(exist_ok=True);maps=[]
NAMES={'original_gnn':'R0 GNN','corrected_gnn':'R1 GNN','original_no_message':'R0 no-message','corrected_no_message':'R1 no-message','chemistry_tree':'Chemistry tree','token_cnn':'Token CNN','guide_ridge':'Guide ridge','pairwise_ridge':'Pairwise ridge','training_row_mean':'Training row mean','training_equal_group_mean':'Training group mean','oracle_test_mean_diagnostic':'Oracle test mean','activity_gnn':'Activity GNN','pair_gnn':'Pair GNN','pair_no_message':'Pair no-message','pair_tree':'Pair tree','pair_ridge':'Pair ridge','training_mean':'Training mean','zero':'Zero','training_majority':'Majority direction','zero_interaction':'Zero interaction'}
COHORT={'ENsiRNA_grouped':'Grouped ENsiRNA','APP':'APP follow-up','Davis_S7':'Davis S7 follow-up'}
def read(n):return pd.read_csv(RUN/n)
def esc(x):
 if pd.isna(x):return 'undefined'
 s=str(x);value=''.join({'&':r'\&','%':r'\%','$':r'\$','#':r'\#','_':r'\_','{':r'\{','}':r'\}','~':r'\textasciitilde{}','^':r'\textasciicircum{}','\\':r'\textbackslash{}'}.get(c,c) for c in s)
 return value.replace('deployment',r'deploy\-ment').replace('b2outer',r'b2\allowbreak{}outer').replace('background',r'back\-ground')
def num(x,d=4):
 if x is None or pd.isna(x):return '--'
 return format(float(x),d) if isinstance(d,str) else f'{float(x):.{d}f}'
def label(x):return NAMES.get(str(x),COHORT.get(str(x),str(x)))
def emit(name,headers,body,caption,source,df=None,align=None,long=False,tablelabel=None):
 align='@{}'+(align or ('l'+'r'*(len(headers)-1)))+'@{}';cap=r'\caption{'+caption+'}'+(r'\label{'+tablelabel+'}' if tablelabel else '')
 head=' & '.join(headers)+r'\\\midrule'+'\n';rows='\n'.join(' & '.join(str(x) for x in row)+r'\\' for row in body)
 if long:s=r'\begin{longtable}{'+align+'}\n'+r'\toprule'+'\n'+head+r'\endfirsthead'+'\n'+r'\toprule'+'\n'+head+r'\endhead'+'\n'+rows+'\n'+r'\bottomrule'+'\n'+cap+r'\\'+'\n'+r'\end{longtable}'+'\n'
 else:s=r'\begin{table}[t]'+'\n'+r'\centering\begin{tabular}{'+align+'}\n'+r'\toprule'+'\n'+head+rows+'\n'+r'\bottomrule\end{tabular}'+'\n'+cap+'\n'+r'\end{table}'+'\n'
 s=s.replace('−',r'\ensuremath{-}')
 (T/f'{name}.tex').write_text(s)
 (df if df is not None else pd.DataFrame(body,columns=headers)).to_csv(T/f'{name}.csv',index=False)
 maps.append(dict(output=f'tables/{name}.tex',source=[dict(path=x,sha256=sha(RUN/x)) for x in source],rows=body,headers=headers,aggregation=caption,generator_sha256=sha(HERE/'paper.py')))
def section(name,text): (P/'sections'/f'{name}.tex').write_text(text+'\n')
a=read('tables/activity_metrics.csv');s=read('tables/seed_stability.csv');d=read('tables/direct_comparisons.csv');b=read('tables/pair_metrics.csv');bc=read('tables/pair_comparisons.csv');rank=read('tables/ranking_summary.csv');b3=read('tables/b3_metrics.csv');fit=read('tables/all_fit_summary.csv');rows=rows_all()+readlines(PREV/'external_observations.jsonl');meta=pd.DataFrame(rows);summary=json.loads((RUN/'evaluation_summary.json').read_text());b3sum=json.loads((RUN/'b3_primary/evaluation_summary.json').read_text());dis=json.loads((RUN/'sources/primary_release_discrepancies.json').read_text())
def ar(c,m,w='rows'):return a[(a.cohort==c)&(a.method==m)&(a.weighting==w)].iloc[0]
def sr(c,m,w='rows'):return s[(s.cohort==c)&(s.method==m)&(s.weighting==w)].iloc[0]
def dr(c,x,y,w='rows'):return d[(d.cohort==c)&(d.a==x)&(d.b==y)&(d.weighting==w)].iloc[0]
def br(m,w='rows'):return b[(b.method==m)&(b.weighting==w)].iloc[0]
def cr(x,y,w='rows'):return bc[(bc.a==x)&(bc.b==y)&(bc.weighting==w)].iloc[0]
mac={'NRows':int(ar('ENsiRNA_grouped','corrected_gnn').n+ar('APP','corrected_gnn').n),'NEnsi':int(ar('ENsiRNA_grouped','corrected_gnn').n),'NApp':int(ar('APP','corrected_gnn').n),'NSseven':int(ar('Davis_S7','corrected_gnn').n),'NAppPools':int(rank.pools.max()),'NBpairs':int(br('pair_gnn').n),'NBbackgrounds':pd.read_csv(RUN/'pair_predictions.csv').background_id.nunique(),'NBcomponents':pd.read_csv(RUN/'pair_predictions.csv').sequence_group.nunique(),'NBthreeConditions':b3sum['conditions'],'NBthreeRectangles':b3sum['rectangles'],'NNewFits':summary['actual_fits'],'NNewUpdates':summary['executed_updates'],'NSelectedUpdates':summary['selected_updates']}
(T/'macros.tex').write_text('\n'.join('\\newcommand{\\'+k+'}{'+f'{v:,}'+'}' for k,v in mac.items())+'\n');write(RUN/'manuscript_macros.json',mac)
# Main data table: units named precisely and current split role visible.
data=[]
for c in ['ENsiRNA_grouped','APP','Davis_S7']:
 z=ar(c,'corrected_gnn');data.append([COHORT[c],str(int(z.n)),str(int(z.sequence_components)),str(int(z.study_linked_groups)),str(int(z.source_families))])
data.append(['Primary B3',str(b3sum['conditions']),'1','1','1'])
emit('main_data',['Evidence','Rows','Seq. comp.','Study links','Sources'],data,r'Observed evaluation units. ENsiRNA is a released-label grouped benchmark; APP is one related patent family and S7 one previously inspected source. B3 has one sequence background. Historical training has four absent directed relation types and only two mismatch edges; Figure~\ref{fig:support} reports current counts and gradients. These are grouping safeguards, not independent biological replicate counts.',['tables/activity_metrics.csv','b3_primary/evaluation_summary.json','tables/historical_training_relation_counts.csv'],tablelabel='tab:data')
# Main activity table has distinct trained and oracle constants for every cohort.
methods=list(NAMES)[:11];body=[];selected=[]
for m in methods:
 rr=[esc(NAMES[m])]
 for c in ['ENsiRNA_grouped','APP','Davis_S7']:
  q=ar(c,m);rr += [num(q.mse),num(q.r_squared,3)];selected.append(q.to_dict())
 body.append(rr)
emit('main_activity',['Model',r'\shortstack{Grouped\\MSE}','$R^2$',r'\shortstack{APP\\MSE}','$R^2$',r'\shortstack{S7\\MSE}','$R^2$'],body,r'Row-weighted ensemble activity prediction. Each stochastic ensemble averages ten fixed final-seed predictions; ridge is deterministic. Grouped values concatenate the five protected outer tests. Training constants use only the relevant training partition. Oracle test means are diagnostics, not deployable baselines or risk lower bounds. Complete weighting, calibration and seed tables are in Appendix~\ref{app:results}.',['tables/activity_metrics.csv'],pd.DataFrame(selected),tablelabel='tab:activity')

calibration=[];cbody=[]
for c in ['ENsiRNA_grouped','APP','Davis_S7']:
 for m in ['corrected_gnn','corrected_no_message','chemistry_tree','token_cnn']:
  q=ar(c,m);calibration.append(q.to_dict());cbody.append([{'ENsiRNA_grouped':'Grouped','APP':'APP','Davis_S7':'S7'}[c],NAMES[m],num(q.correlation,3),num(q.prediction_sd,4),num(q.label_sd,4),num(q.mean_bias,4)])
emit('main_calibration',['Data','Model','$r$',r'\shortstack{Pred.\\SD}',r'\shortstack{Label\\SD}','Bias'],cbody,r'Discrimination and calibration of fixed ensembles on the original activity scale, with row weighting and no test-fitted adjustment. SD describes empirical spread, not uncertainty of a biological mean. Constant MSE and oracle references are in Table~\ref{tab:activity}; undefined correlations for tied constants appear in the full appendix. Small prediction spread can coexist with a lower MSE through mean calibration.',['tables/activity_metrics.csv'],pd.DataFrame(calibration),align=r'lp{.25\textwidth}rrrr',tablelabel='tab:calibration')

# Main direct comparison table with separate seed SD next to conditional ensemble CI.
sc=read('tables/seed_comparison_stability.csv');body=[];selected=[]
for c in ['ENsiRNA_grouped','APP','Davis_S7']:
 for x,y in [('corrected_gnn','corrected_no_message'),('corrected_gnn','chemistry_tree')]:
  q=dr(c,x,y);z=sc[(sc.cohort==c)&(sc.a==x)&(sc.b==y)&(sc.weighting=='rows')].iloc[0];body.append([{'ENsiRNA_grouped':'Grouped','APP':'APP','Davis_S7':'S7'}[c],NAMES[y],r'\shortstack{'+num(q.difference)+r'\\{}'+f'[{num(q.lower)}, {num(q.upper)}]'+r'}',r'\shortstack{'+num(z['mean'])+r'\\('+num(z['std'])+r')}']);selected.append(dict(q,seed_mean=z['mean'],seed_sd=z['std']))
emit('main_comparisons',['Data','Comparator',r'\shortstack{R1 GNN $- $ comparator\\$\Delta$ MSE [conditional 95\%]}',r'\shortstack{Seed mean\\(seed SD)}'],body,r'Direct matched contrasts; negative favors R1 GNN. The interval resamples whole sequence components 10,000 times with fitted ensembles fixed. The last column summarizes ten matched-seed loss contrasts on the fixed cohort. They target different variation and are not a pooled uncertainty interval. All intervals are unadjusted descriptive comparisons.',['tables/direct_comparisons.csv','tables/seed_comparison_stability.csv'],pd.DataFrame(selected),tablelabel='tab:comparisons')
# Main paired table: regression and direction-only controls explicitly separate.
body=[];selected=[]
for m in ['activity_gnn','pair_gnn','pair_no_message','pair_tree','pair_ridge','zero','training_mean','training_majority']:
 q=br(m);selected.append(q.to_dict());body.append([NAMES[m],num(q.mse),num(br(m,'equal_sequence').mse),num(q.correlation,3),num(q.prediction_sd,3),f'{int(q.non_tie_correct)}/{int(q.non_ties)}'])
emit('main_pair_ranking',['B2 method',r'\shortstack{Row\\MSE}',r'\shortstack{Comp.\\MSE}','$r$',r'\shortstack{Pred.\\SD}',r'\shortstack{Sign/\\non-tie}'],body,r'Measured B2 changed-minus-reference predictions. Comp. MSE gives each of twelve sequence components equal mass. Majority is a sign-only control, so its regression quantities are undefined. The operational sign band is $\pm0.02$. APP ranking is shown in Figure~\ref{fig:pair} and its complete pool table; no B2 error is pooled with a ranking score. These pairs jointly change four guide positions.',['tables/pair_metrics.csv'],pd.DataFrame(selected),tablelabel='tab:pairranking')
body=[];selected=[]
for m in ['corrected_gnn','corrected_no_message','chemistry_tree','token_cnn','zero_interaction']:
 q=b3[(b3.method==m)&(b3.seed.astype(str).isin(['ensemble','deterministic']))].iloc[0];selected.append(q.to_dict());body.append([NAMES[m],num(q.mse),num(q.correlation,3),num(q.prediction_sd,3),num(q.mean_bias,3)])
emit('main_B3',['Primary B3 method','MSE','$r$',r'\shortstack{Pred.\\SD}','Bias'],body,r'Source-held-out prediction of 140 measured four-condition interactions. All share one base-sequence background and common reference; these descriptive metrics have no independent-rectangle interval. No fit or tuning uses this newly admitted panel. APP still has zero four-state blocks.',['tables/b3_metrics.csv'],pd.DataFrame(selected),tablelabel='tab:B3')

# Actual fit effort by task/architecture, not a count of independent datasets.
opt=fit.copy();opt['task']=opt.name.str.split('/').str[0];opt['final']=opt.name.str.contains('/final/');orows=[]
for (task,method),z in opt.groupby(['task','method'],sort=True):
 orows.append(dict(task=task,method=method,development_fits=int((~z.final).sum()),final_fits=int(z.final.sum()),executed_updates=int(z.executed_updates.sum()),selected_updates=int(z.selected_updates.sum())))
o=pd.DataFrame(orows);export(o,'tables/optimization_by_task.csv');emit('main_optimization',['Task','Architecture',r'\shortstack{Dev.\\fits}',r'\shortstack{Final\\fits}',r'\shortstack{Executed\\updates}',r'\shortstack{Selected\\updates}'],[[q.task.title(),NAMES[q.method],str(q.development_fits),str(q.final_fits),f'{q.executed_updates:,}',f'{q.selected_updates:,}'] for q in o.itertuples()],'Executed optimization effort. Activity spans five protected outer tests and deployment; pair spans four protected outer tests. The pair R1 GNN row includes activity-only and pair-supervised fits. Development includes all candidates, not just winners. Zero updates for trees/ridge mean non-neural fits, not missing training. Every stochastic final block contains ten seeds; no failed core fit or test-driven restart occurred.',['tables/optimization_by_task.csv','tables/all_fit_summary.csv'],o,align=r'lp{.25\textwidth}rrrr',tablelabel='tab:optimization')

# Numeric prose, generated only from the exports.
def conditional(q):return 'lower conditional ensemble MSE' if q.upper<0 else 'higher conditional ensemble MSE' if q.lower>0 else 'no resolved conditional ensemble difference'
app=dr('APP','corrected_gnn','chemistry_tree');nm=dr('APP','corrected_gnn','corrected_no_message');pairmean=cr('pair_gnn','training_mean','equal_groups')
bestrow=a[(a.cohort=='APP')&(a.weighting=='rows')&~a.method.isin(['original_gnn','corrected_gnn','oracle_test_mean_diagnostic'])].sort_values('mse').iloc[0];bestname=bestrow.method;bestcontrast=dr('APP','corrected_gnn',bestname)
spfile=RUN/'fits/activity/deployment/final/original_gnn/s1103/preprocessing.json';sp=json.loads(spfile.read_text());support_values=dict(training_rows=len(sp['training_record_ids']),retained_node_columns=sum(sp['node_support']),varying_context_columns=sum(sp['context_varying']),directed_relation_counts=sp['directed_relation_counts'],source=str(spfile.relative_to(RUN)),sha256=sha(spfile));write(RUN/'manuscript_support_values.json',support_values)
section('support_results',f"The deployment parameter-update partition contains {len(sp['training_record_ids']):,} rows. Its mask retains {sum(sp['node_support'])} of 93 node-feature columns and {sum(sp['context_varying'])} of eight context coordinates; the remaining context fields are constant in training. Thus the current predictor's available chemistry and assay information is narrower than the full input schema.")
section('fit_outcomes',f'The finite core matrix completed {len(fit):,} fits with {int((fit.status!="completed").sum()):,} failed fits, {int(fit.executed_updates.sum()):,} executed optimizer updates and {int(fit.selected_updates.sum()):,} selected-checkpoint updates. These totals include development; a checkpoint hash check is not another fit.')
section('abstract_results',f'Across {len(fit):,} core fits, the corrected GNN has APP MSE {num(ar("APP","corrected_gnn").mse)}, compared with {num(bestrow.mse)} for the strongest observed fitted baseline ({NAMES[bestname]}). This descriptive baseline selection uses the reported follow-up errors. The direct comparison gives {conditional(bestcontrast)}. The measured pair comparison against its training-fold mean gives {conditional(pairmean)}.')
q=ar('Davis_S7','corrected_gnn');ss=sr('APP','corrected_gnn');support=dr('APP','corrected_gnn','original_gnn')
section('activity_results',f'On APP, R1 GNN minus the tree is {num(app.difference)} [{num(app.lower)}, {num(app.upper)}]; the direct no-message contrast is {num(nm.difference)} [{num(nm.lower)}, {num(nm.upper)}]. Thus the two direct comparisons show {conditional(app)} versus the tree and {conditional(nm)} versus no-message. R1 minus R0 GNN is {num(support.difference,6)} [{num(support.lower,6)}, {num(support.upper,6)}]. This outcome, rather than support presence alone, determines the predictive interpretation of the correction.\n\nR1 GNN APP ensemble MSE is {num(ar("APP","corrected_gnn").mse)}, whereas mean member MSE is {num(ss.mean_seed_mse)} (SD {num(ss.sd_seed_mse)}, range {num(ss.min_seed_mse)}--{num(ss.max_seed_mse)}). On S7 its MSE is {num(q.mse)} and descriptive $R^2$ is {num(q.r_squared,3)}. Its prediction SD {num(q.prediction_sd,3)}, label SD {num(q.label_sd,3)} and mean bias {num(q.mean_bias,3)} expose discrimination and calibration separately.')
pairq=br('pair_gnn');rval={m:float(rank[rank.method==m].iloc[0].top5_mean_percentile) for m in ['corrected_gnn','chemistry_tree','corrected_no_message']}
section('pair_results',f'The pair-supervised GNN has row MSE {num(pairq.mse)} and equal-component MSE {num(br("pair_gnn","equal_sequence").mse)}. Its equal-component difference from the training-fold mean is {num(pairmean.difference)} [{num(pairmean.lower)}, {num(pairmean.upper)}], giving {conditional(pairmean)}. Predicted-measured difference correlation is {num(pairq.correlation,3)}; predicted and observed SDs are {num(pairq.prediction_sd,3)} and {num(pairq.label_sd,3)}.\n\nAPP mean top-five percentile is {num(rval["corrected_gnn"])} for R1 GNN, {num(rval["chemistry_tree"])} for the tree and {num(rval["corrected_no_message"])} for R1 no-message, against exact random-tie expectation 0.5. These descriptive ranking comparisons need not agree with the MSE ordering.')
q=b3[(b3.method=='corrected_gnn')&(b3.seed.astype(str)=='ensemble')].iloc[0];z=b3[b3.method=='zero_interaction'].iloc[0]
section('b3_results',r'\input{tables/main_B3}'+f'R1 GNN interaction MSE is {num(q.mse)}, compared with {num(z.mse)} for zero interaction; the measured-predicted correlation is {num(q.correlation,3)}. Appendix~\\ref{{app:b3}} gives every primary state and condition.')
section('published_status',r'Exact published-baseline reproduction remains incomplete. The official ENsiRNA-mod geometry archive could not be retrieved and its configured Rosetta generator is absent. The MEG-mod release lacks a complete modification-token forward path. Ordinary dependency and acquisition attempts are recorded; zero exact published predictors were fitted. Available representation assets are not presented as completed efficacy training.')
positive=bestcontrast.upper<0;within=read('tables/B2_within_assay_variation.csv');wv=within[within.method=='pair_gnn'].iloc[0];pairpositive=pairmean.upper<0 and pairq.correlation>0 and pd.notna(wv.conditional_correlation_lower) and wv.conditional_correlation_lower>0
section('conclusion_results',(f'The fixed APP comparison supports a conditional R1 GNN advantage over the strongest observed fitted baseline, {NAMES[bestname]}; baseline selection here is descriptive from the follow-up table.' if positive else 'A general GNN advantage is not established: the direct conditional comparisons and seed variability must be read on their stated cohorts.')+' '+('The measured B2 comparison supports an improvement over the training-fold mean within this observed bundle and grouping design; it does not establish a new-study or isolated-chemistry effect.' if pairpositive else 'Sequence-specific measured chemistry prediction is not established beyond the training-fold mean under the declared B2 comparison.'))

# Interpretation paragraphs are also generated from full-precision current exports.
appmetric=ar('APP','corrected_gnn');identity=read('tables/matched_support_training_identity.csv');ni=int(identity.selected_parameters_bit_identical.sum());assert identity.same_selected_configuration.all();s7corr=dr('Davis_S7','corrected_gnn','original_gnn');s7nm=dr('Davis_S7','corrected_no_message','original_no_message');di=d[(d.cohort=='Davis_S7')&(d.a=='support_by_message_interaction')].iloc[0]
with (P/'sections/support_results.tex').open('a') as out:out.write(f' All {ni} of {len(identity)} matched R0/R1 final pairs have identical selected parameter tensors and selected configurations; their held-out routing can still differ.\n')
with (P/'sections/activity_results.tex').open('a') as out:
 out.write(f'\nOn APP, R1 GNN prediction SD is {num(appmetric.prediction_sd,4)} against label SD {num(appmetric.label_sd,4)}, with correlation {num(appmetric.correlation,3)}. The improved tree contrast therefore accompanies nearly constant predictions, not established candidate discrimination. On S7, R1 minus R0 MSE is {num(s7corr.difference,6)} for GNN and {num(s7nm.difference,6)} for no-message; the joint support-by-message contrast is {num(di.difference,6)} [{num(di.lower,6)}, {num(di.upper,6)}]. The correction does not establish a benefit specific to message passing.\n')
epmetrics=read('tables/pair_endpoint_metrics.csv');epp={m:epmetrics[(epmetrics.method==m)&(epmetrics.seed.astype(str)=='ensemble')].iloc[0] for m in ['activity_gnn','pair_gnn','pair_no_message']}
with (P/'sections/pair_results.tex').open('a') as out:
 out.write(f'\nAfter explicitly diagnostic within-assay centering, pair-GNN correlation is {num(wv.correlation,3)} [{num(wv.conditional_correlation_lower,3)}, {num(wv.conditional_correlation_upper,3)}]. All {int(pairq.negative_calls)} pair-GNN predictions have negative operational signs, matching the majority-direction control. Equal-sequence endpoint MSE is {num(epp["activity_gnn"].mse)} for activity-only GNN, {num(epp["pair_gnn"].mse)} for pair GNN and {num(epp["pair_no_message"].mse)} for pair no-message. Pair supervision improves some descriptive errors without establishing sequence-specific chemistry prediction.\n')


qg=ar('ENsiRNA_grouped','corrected_gnn');qt=ar('ENsiRNA_grouped','chemistry_tree');qc=ar('ENsiRNA_grouped','training_row_mean');qgc=dr('ENsiRNA_grouped','corrected_gnn','chemistry_tree');qgn=dr('ENsiRNA_grouped','corrected_gnn','corrected_no_message')
section('grouped_interpretation',f'Grouped ENsiRNA prediction gives tree MSE {num(qt.mse)} and R1 GNN MSE {num(qg.mse)}, compared with {num(qc.mse)} for the fold-specific training-row constant. The GNN--tree interval [{num(qgc.lower)}, {num(qgc.upper)}] and GNN--no-message interval [{num(qgn.lower)}, {num(qgn.upper)}] both include zero. Correlation is {num(qg.correlation,3)} for GNN and {num(qt.correlation,3)} for the tree. This protected grouped benchmark offers some discrimination, but does not establish that neighbor-state exchange improves the selected procedure. Its labels retain the primary-source limitation below.')
section('source_interpretation',f'Identity-based reconciliation matches {dis["identity_matched_pairs"]:,} Bramsen primary/released values; {dis["greater_than_five_percentage_points"]:,} differ by more than 0.05 on the activity scale, with maximum absolute discrepancy {num(dis["max_absolute_activity_difference"],4)}. Matching uses base sequences and positional chemistry, not outcome agreement or model predictions. Some smaller differences reflect rounding. Larger discrepancies require source curation; the present check does not prove that each mismatch is a biological measurement error. The frozen labels are retained for an auditable benchmark comparison rather than retrospectively replaced after model evaluation.\n\nThe recovered B3 panel uses the primary normalized eGFP measurements directly, under its separate admission rule. It contains whole-antisense and whole-sense chemistry changes at fixed base sequences, not the APP guide-position bundle. Its single background, common reference and unresolved shared-control covariance preclude independent-rectangle uncertainty or across-sequence validation. The accompanying viability values are preserved as source evidence but were not an admission filter or prediction target; reduced eGFP is not thereby shown to be independent of viability or equivalent to direct mRNA knockdown.')

# Full unabridged tables use bounded-width columns and every numeric row.
# Stable compact identifiers keep all-fit tables readable; full mapping is printed separately.
fitids={n:f'F{i+1:04d}' for i,n in enumerate(sorted(fit.name))};write(RUN/'fit_display_ids.json',fitids)
config_names=sorted(set(fit.configuration));config_codes={x:f'H{i+1}' for i,x in enumerate(config_names)}
path_codes={'activity':'A','pair':'P','original_gnn':'R0G','corrected_gnn':'R1G','original_no_message':'R0N','corrected_no_message':'R1N','token_cnn':'CNN','chemistry_tree':'ET','guide_ridge':'GR','pairwise_ridge':'PR','activity_gnn':'AG','pair_gnn':'PG','pair_no_message':'PN','pair_ridge':'DR','pair_tree':'DT',**config_codes}
def shortpath(x):return '/'.join(path_codes.get(z,z) for z in x.split('/'))
emit('appendix_config_codes',['Code','Exact configuration token'],[[config_codes[k],esc(k)] for k in config_names],'Closed configuration-token dictionary for the complete fit tables. These tokens expand to the exact learning-rate/weight-decay, ridge alpha or tree-leaf settings.',['protocol.json','tables/all_fit_summary.csv'],align='lp{.75\\textwidth}',long=True)
emit('appendix_path_codes',['Path token','Exact expansion'],[[v,esc(k)] for k,v in path_codes.items() if k not in config_codes],'Closed path dictionary. Replace each whole token to recover the exact fit directory; all slashes and unlisted tokens remain literal. Configuration H tokens use the preceding dictionary. No external lookup is needed.',['tables/all_fit_summary.csv'],align='lp{.75\\textwidth}',long=True)
def full(name,source,cols,headers,caption,fmt=None,align=None,labelname=None):
 df=read(source);body=[]
 for row in df.to_dict('records'):
  vals=[]
  for c in cols:
   v=row[c]
   if c in ['method','a','b']:v=label(v)
   elif c=='cohort':v=label(v)
   elif c=='seed':v={'ensemble':'Ens.','deterministic':'D','training_constant':'T','oracle':'O'}.get(str(v),v)
   elif c=='kind':v={'activity_config':'Act cfg','pair_lambda':'Pair weight'}.get(str(v),v)
   elif c in ['fit','name','original_fit','corrected_fit']:v=fitids.get(v,v)
   elif c=='configuration':v=config_codes.get(v,v)
   if isinstance(v,(float,np.floating)) and np.isfinite(v) and v.is_integer() and c in ['n','seed','training_n','validation_n','test_n','parameters','selected_epoch','epochs_executed','selected_updates','executed_updates','non_tie_correct','non_ties','negative_calls','zero_calls','positive_calls','sequence_components','study_linked_groups','source_families']:v=int(v)
   if fmt and c in fmt:v=num(v,fmt[c])
   vals.append(r'\texttt{\seqsplit{'+esc(v)+'}}' if c in ['sequence','guide_sequence','passenger_sequence'] else esc(v).replace(r'\_',r'\_\allowbreak{}').replace('/',r'/\allowbreak{}').replace('|',r'|\allowbreak{}').replace(':',r':\allowbreak{}'))
  body.append(vals)
 emit(name,headers,body,caption,[source],df,align=align,long=True,tablelabel=labelname)
# Main metrics split into two synchronized tables: no columns are silently omitted.
full('appendix_activity_errors','tables/activity_metrics.csv',['cohort','method','weighting','n','mse','mae','r_squared'],['Cohort','Method','Weights','$n$','MSE','MAE','$R^2$'],'Every current cohort, arm and weighting, including fitted/oracle constants.',fmt={'mse':6,'mae':6,'r_squared':5},align='p{.11\\textwidth}p{.21\\textwidth}p{.12\\textwidth}rrrr')
full('appendix_activity_calibration','tables/activity_metrics.csv',['cohort','method','weighting','correlation','prediction_sd','label_sd','mean_bias'],['Cohort','Method','Weights','$r$',r'\shortstack{Pred.\\SD}',r'\shortstack{Label\\SD}','Bias'],'Full activity discrimination, spread and calibration on the same rows as the error table.',fmt={c:5 for c in ['correlation','prediction_sd','label_sd','mean_bias']},align='p{.11\\textwidth}p{.21\\textwidth}p{.12\\textwidth}rrrr')
full('appendix_seed_metrics','tables/activity_seed_metrics.csv',['cohort','method','seed','weighting','mse','correlation','mean_bias'],['Cohort','Method','Seed','Weights','MSE','$r$','Bias'],'Every final seed and weighting. Deterministic ridge has one seed identifier, not ten independent fits.',fmt={'mse':6,'correlation':4,'mean_bias':4},align='p{.13\\textwidth}p{.20\\textwidth}rp{.13\\textwidth}rrr')
full('appendix_direct_comparisons','tables/direct_comparisons.csv',['cohort','a','b','weighting','difference','lower','upper'],['Cohort','A','B','Wt.',r'$\Delta$','Lower','Upper'],'All direct conditional loss comparisons and the four-ensemble support-by-message interaction; negative favors A. Same weights recomputed in every one of 10,000 resamples.',fmt={c:6 for c in ['difference','lower','upper']},align='p{.10\\textwidth}p{.14\\textwidth}p{.14\\textwidth}p{.08\\textwidth}rrr')
full('appendix_pair_metrics','tables/pair_metrics.csv',['method','weighting','mse','mae','correlation','prediction_sd','mean_bias'],['Method','Weights','MSE','MAE','$r$',r'\shortstack{Pred.\\SD}','Bias'],'All B2 regression metrics. Majority is a direction-only control with undefined regression performance.',fmt={c:5 for c in ['mse','mae','correlation','prediction_sd','mean_bias']},align='p{.22\\textwidth}p{.14\\textwidth}rrrrr')
full('appendix_pair_signs','tables/pair_metrics.csv',['method','weighting','sign_accuracy','non_tie_correct','non_ties','negative_calls','zero_calls','positive_calls'],['Method','Weights','Acc.','Correct',r'\shortstack{Non-\\ties}','Neg.','Zero','Pos.'],'B2 operational sign calls under the unchanged band; counts are rows, while weighted accuracy follows the named weights.',fmt={'sign_accuracy':5},align='p{.20\\textwidth}p{.13\\textwidth}rrrrrr')
full('appendix_pair_comparisons','tables/pair_comparisons.csv',['a','b','weighting','difference','lower','upper'],['A','B','Weights',r'$\Delta$','Lower','Upper'],'All direct fixed-ensemble B2 error comparisons; twelve sequence components resampled, with no new-laboratory coverage claim.',fmt={c:6 for c in ['difference','lower','upper']},align='p{.18\\textwidth}p{.20\\textwidth}p{.14\\textwidth}rrr')
full('appendix_pair_seeds','tables/pair_seed_metrics.csv',['method','seed','weighting','mse','correlation','prediction_sd','mean_bias'],['Method','Seed','Weights','MSE','$r$',r'\shortstack{Pred.\\SD}','Bias'],'Every pair seed and weighting; no unfavorable seed removed.',fmt={c:5 for c in ['mse','correlation','prediction_sd','mean_bias']},align='p{.21\\textwidth}rp{.14\\textwidth}rrrr')
full('appendix_pair_endpoint','tables/pair_endpoint_metrics.csv',['method','seed','n','mse','mae','correlation','prediction_sd','mean_bias'],['Endpoint method','Seed','$n$','MSE','MAE','$r$',r'\shortstack{Pred.\\SD}','Bias'],'Endpoint activity performance accompanies pair error; these are equal-sequence metrics, with ensemble risk distinct from member risks.',fmt={c:5 for c in ['mse','mae','correlation','prediction_sd','mean_bias']},align='p{.21\\textwidth}rrrrrrr')
full('appendix_ranking','tables/ranking_pools.csv',['method','pool','n','sequence_components','top5_mean_percentile','selected_mean_activity','cutoff_ties'],['Method','Pool','$n$','Seq.','Top five','Activity','Ties'],'Every APP pool and method with exact boundary ties. Pool identifiers encode actual primary assay; overlap table follows.',fmt={'top5_mean_percentile':5,'selected_mean_activity':5},align='p{.18\\textwidth}p{.27\\textwidth}rrrrr')
full('appendix_B3_metrics','tables/b3_metrics.csv',['method','seed','mse','mae','correlation','prediction_sd','mean_bias'],['B3 method','Seed','MSE','MAE','$r$',r'\shortstack{Pred.\\SD}','Bias'],'All ten source-held-out members, ensembles and the zero reference on measured primary B3 contrasts; one background, no independent-rectangle CI. Near-zero finite-precision ridge contrasts are not chemistry signal.',fmt={c:5 for c in ['mse','mae','correlation','prediction_sd','mean_bias']},align='p{.23\\textwidth}rrrrrr')
full('appendix_B3_measurements','tables/b3_primary_measurements.csv',['AS','SS','y00','y10','y01','y11','interaction'],['AS','SS','$y_{00}$','$y_{10}$','$y_{01}$','$y_{11}$','$I$'],'All primary measured four-condition values, activity = one minus normalized eGFP; repeated references are explicit.',fmt={c:6 for c in ['y00','y10','y01','y11','interaction']},align='llrrrrr')
full('appendix_B3_states','tables/b3_primary_states.csv',['state','strand','sequence','modifications'],['State','Strand','Bases','Positional chemistry'],'Every admitted primary state and its explicit aliases. Positions are one-based; unlisted positions retain the source unmodified convention.',align='p{.11\\textwidth}p{.08\\textwidth}p{.27\\textwidth}p{.41\\textwidth}')
alias=json.loads((RUN/'b3/mapping_rules.json').read_text())['aliases'];emit('appendix_b3_aliases',['Primary subscript','Frozen name'],[[esc(k),esc(v)] for k,v in alias.items()],'Literal source aliases used in primary B3 admission. AP remains unresolved and excluded.',['b3/mapping_rules.json'],align='p{.20\\textwidth}p{.70\\textwidth}',long=True,tablelabel='tab:b3aliases')
emit('appendix_source_discrepancies',['Reconciliation diagnostic','Count/value'],[[esc(k),esc(v)] for k,v in dis.items() if k!='interpretation'],'Primary/release audit conditional on the stated identity mapping. Rounding tolerances are activity fractions; no frozen label is changed.',['sources/primary_release_discrepancies.json'],align='p{.72\\textwidth}r',long=True,tablelabel='tab:source_discrepancies')
full('appendix_fits','tables/all_fit_summary.csv',['name','method','seed','configuration','validation_score'],['Fit','Method','Seed','Config.','Val. MSE'],'Every planned core fit, with exact configuration and validation score. Compact IDs map to the complete path dictionary. Classical estimators remain real fits; their zero optimizer counts are in the next panel.',fmt={'validation_score':5},align=r'lp{.25\textwidth}rlr')
full('appendix_fit_optimization','tables/all_fit_summary.csv',['name','selected_epoch','epochs_executed','selected_updates','executed_updates'],['Fit',r'\shortstack{Selected\\epoch}',r'\shortstack{Executed\\epochs}',r'\shortstack{Selected\\updates}',r'\shortstack{Executed\\updates}'],'Every actual selected and executed optimizer count. The entire trajectory is executed even when the selected checkpoint is early; deterministic/tree estimators have zero neural updates.',align='lrrrr')
emit('appendix_fit_paths',['ID','Exact fit path'],[[v,esc(shortpath(k)).replace('/',r'/\allowbreak{}')] for k,v in fitids.items()],'Complete fit identifier mapping under the closed path/configuration dictionaries above. Expansion gives every exact directory without omitting a fit; each retains signatures, parameters, histories and checkpoints.',['tables/all_fit_summary.csv'],align='lp{.83\\textwidth}',long=True)
full('appendix_selection','tables/selection_scores.csv',['population','method','kind','configuration','validation_score','selected'],['Population','Method','Selection','Config.','$V$','Chosen'],'Every candidate validation score and selection outcome. The selection design is frozen; no APP/S7 metric enters this table.',fmt={'validation_score':6},align='lp{.21\\textwidth}p{.16\\textwidth}lrl')
full('appendix_fold_seeds','tables/per_fold_seed_metrics.csv',['cohort','population','method','seed','n','mse','correlation','mean_bias'],['Cohort','Outer','Method','Seed','$n$','MSE','$r$','Bias'],'Every final fold and seed on its actual held-out rows.',fmt={'mse':6,'correlation':4,'mean_bias':4},align='p{.12\\textwidth}p{.10\\textwidth}p{.18\\textwidth}rrrrr')
full('appendix_assays','tables/per_assay_metrics.csv',['cohort','method','assay','n','mse','correlation','mean_bias'],['Cohort','Method','Assay','$n$','MSE','$r$','Bias'],'Every assay/cohort/ensemble, including separate trained constants and descriptive assay oracle means. Unresolved assay identifiers remain explicitly unresolved.',fmt={'mse':6,'correlation':4,'mean_bias':4},align='p{.10\\textwidth}p{.15\\textwidth}p{.22\\textwidth}rrrr')
full('appendix_structural','tables/structural_parameter_counts.csv',['fit','method','seed','inactive_input_scalars','inactive_readout_scalars','inactive_relation_scalars','train_reachable_upper_bound'],['Fit','Method','Seed',r'\shortstack{Input\\zero}',r'\shortstack{Readout\\zero}',r'\shortstack{Relation\\zero}',r'\shortstack{Reachable\\$\leq$}'],'All final graph/no-message structural counts. Remaining scalars are only an upper bound on data-reachable parameters, not proof of nonzero realized gradients. Total is 153,345 for each row.',align='lp{.19\\textwidth}rrrrr')
for half in [0,1]:
 rels=list(range(half*4,half*4+4))
 full('appendix_gradients'+('' if half==0 else '_second'),'tables/final_parameter_support.csv',['fit','layer']+[f'g{i}' for i in rels],['Fit','Layer']+[['PO+','PS+','?+','PO−','PS−','?−','Pair','Mismatch'][i] for i in rels],'Every final graph/no-message layer and seed data-gradient norm; scientific notation preserves rare nonzero gradients. Selected checkpoint, dropout disabled; activity loss alone, including pair-trained networks.',fmt={f'g{i}':'.3e' for i in rels},align=r'lp{.20\textwidth}rrrr')
 full('appendix_parameter_deltas'+('' if half==0 else '_second'),'tables/final_parameter_support.csv',['fit','layer']+[f'delta{i}' for i in rels],['Fit','Layer']+[['PO+','PS+','?+','PO−','PS−','?−','Pair','Mismatch'][i] for i in rels],'Per-relation selected-checkpoint L1 parameter change from initialization. Includes AdamW weight decay and does not certify a nonzero data gradient.',fmt={f'delta{i}':'.3e' for i in rels},align=r'lp{.20\textwidth}rrrr')

# Full fit records are supplemented by compressed exact training-partition evidence.
parts=read('tables/training_partition_groups.csv');emit('appendix_partition_groups',['Partition','Study component','Rows','Seq.','Sources'],[[esc(x.partition),esc(x.study_group),x.rows,x.sequence_components,esc(x.source_labels).replace(r'\_',r'\_\allowbreak{}').replace('|',r'|\allowbreak{}')] for x in parts.itertuples()],'Every distinct training partition and its protected study/source membership; no outcome-based grouping.',['tables/training_partition_groups.csv'],parts,align='lp{.22\\textwidth}rrp{.25\\textwidth}',long=True)
fe=read('tables/feature_support_counts.csv');body=[]
for part,z in fe.groupby('partition'):
 body.append([esc(part),str(int(z.active_training_nodes.iloc[0])),esc(', '.join(f'{int(x.feature)}:{int(x.nonzero_training_nodes)}' for x in z.itertuples()))])
emit('appendix_features',['Partition',r'\shortstack{Active\\nodes}','Coordinate: nonzero-node count (all 93)'],body,'Every feature count on actual active training nodes. A zero count disables that feature in all roles; nonzero is presence, not adequacy.',['tables/feature_support_counts.csv'],fe,align='lrp{.62\\textwidth}',long=True)
full('appendix_seed_spread','tables/activity_seed_metrics.csv',['cohort','method','seed','weighting','mae','r_squared','prediction_sd','label_sd'],['Cohort','Method','Seed','Weights','MAE','$R^2$',r'\shortstack{Pred.\\SD}',r'\shortstack{Label\\SD}'],'Remaining diagnostics for every final seed and weighting; same exact prediction records as the preceding seed-error table.',fmt={c:5 for c in ['mae','r_squared','prediction_sd','label_sd']},align='p{.09\\textwidth}p{.16\\textwidth}rp{.11\\textwidth}rrrr')
full('appendix_seed_differences','tables/seed_paired_differences.csv',['cohort','a','b','seed','weighting','difference'],['Cohort','A','B','Seed','Weights',r'$\Delta$'],'All matched-seed activity loss differences, separately from fixed-ensemble bootstrap uncertainty.',fmt={'difference':6},align='p{.12\\textwidth}p{.21\\textwidth}p{.21\\textwidth}rp{.14\\textwidth}r')
full('appendix_pair_seed_differences','tables/pair_seed_differences.csv',['a','b','seed','weighting','difference'],['A','B','Seed','Weights',r'$\Delta$'],'Every paired B2 seed contrast, including the training-fold mean and activity-only comparator.',fmt={'difference':6},align='p{.22\\textwidth}p{.24\\textwidth}rp{.16\\textwidth}r')
full('appendix_assay_spread','tables/per_assay_metrics.csv',['cohort','method','assay','mae','r_squared','prediction_sd','label_sd'],['Cohort','Method','Assay','MAE','$R^2$',r'\shortstack{Pred.\\SD}',r'\shortstack{Label\\SD}'],'Remaining calibration/discrimination diagnostics for every assay, including appropriate constant rows.',fmt={c:5 for c in ['mae','r_squared','prediction_sd','label_sd']},align='p{.09\\textwidth}p{.14\\textwidth}p{.22\\textwidth}rrrr')
full('appendix_B3_sds','tables/b3_primary_measurements.csv',['AS','SS','sd00','sd10','sd01','sd11'],['AS','SS','SD 00','SD 10','SD 01','SD 11'],'Every primary B3 endpoint SD, preserved on the response-fraction scale. SDs are not SEs and do not supply shared-control covariance.',fmt={c:6 for c in ['sd00','sd10','sd01','sd11']},align='llrrrr')
# Exact pair identities contain all endpoint SDs and orientations.
pp=read('pair_predictions.csv').drop_duplicates('pair_id');pbody=[]
for q in pp.itertuples():pbody.append([r'\seqsplit{'+esc(q.pair_id)+'}',r'\seqsplit{'+esc(q.reference_id)+'}',r'\seqsplit{'+esc(q.changed_id)+'}',r'\seqsplit{'+esc(q.sequence_group)+'}',num(q.observed_difference,6),num(q.measurement_sd_reference,5),num(q.measurement_sd_changed,5)])
emit('appendix_pair_identities',['Pair','Reference ID','Changed ID','Sequence group','$d$','SD ref.','SD changed'],pbody,'All B2 identities, measured orientation and endpoint SDs. Exact chemistry/assay/background mappings are retained in the accompanying CSV; no mean-difference SE is manufactured.',['pair_predictions.csv'],pp,align='p{.11\\textwidth}p{.13\\textwidth}p{.13\\textwidth}p{.14\\textwidth}rrr',long=True)
# Alias long identifiers once, then show compact but fully mapped pool comparisons.
pools=read('tables/ranking_direct_pool_differences.csv');poolids={x:f'P{i+1}' for i,x in enumerate(pools.pool)}
emit('appendix_pool_differences',['Pool','Exact assay identifier','Tree − GNN','GNN − no-msg'],[[poolids[q.pool],esc(q.pool).replace(r'\_',r'\_\allowbreak{}').replace('|',r'|\allowbreak{}'),num(q.tree_minus_corrected_gnn,6),num(q.corrected_gnn_minus_no_message,6)] for q in pools.itertuples()],'Exact pool mapping and both direct tie-aware percentile differences.',['tables/ranking_direct_pool_differences.csv'],pools,align='lp{.56\\textwidth}rr',long=True)
ov=read('tables/ranking_pool_overlap.csv');emit('appendix_pool_overlap',['Pool A','Pool B','Shared sequence components'],[[poolids[q.pool_a],poolids[q.pool_b],q.shared_sequence_components] for q in ov.itertuples()],'Every pool-pair overlap, including zero; these dependence counts are not independent-study counts.',['tables/ranking_pool_overlap.csv'],ov,align='llr',long=True)
full('appendix_fit_details','tables/all_fit_summary.csv',['name','training_n','validation_n','test_n','parameters','status'],['Fit','Train','Val.','Test','Size','Status'],'Every fit population, size and failure status. Size is scalar count for neural/ridge, total tree nodes for activity tree, and undefined when not recorded for direct pair estimators. Pair classical input counts are pairs; neural counts are endpoints.',align='lrrrrl')
full('appendix_fit_scaling','tables/all_fit_summary.csv',['name','target_mean','target_sd','lambda_pair','selection'],['Fit',r'$\mu_T$',r'$s_T$',r'$\lambda$','Checkpoint score'],'Every recorded target scaling, pair coefficient and selection target. Missing direct-estimator fields are shown as undefined, not invented.',fmt={'target_mean':5,'target_sd':5,'lambda_pair':1},align='lrrrl')
# Per-role counts are identical across matched seeds but all rows remain available in CSV; print each unique population/method/role support vector.
rr=read('tables/final_relation_counts.csv');rr['population']=rr.fit.str.split('/').str[1];vectors=rr.groupby(['population','method','role','relation'],as_index=False).directed_edges.agg(['min','max']).reset_index();assert (vectors['min']==vectors['max']).all();pivot=vectors.pivot(index=['population','method','role'],columns='relation',values='min').reset_index()
for half in [0,1]:
 indices=list(range(4*half,4*half+4));labels=['PO+','PS+','?+','PO−','PS−','?−','Pair','Mis.'];emit('appendix_relation_counts'+('' if half==0 else '_second'),['Population','Method','Role']+[labels[i] for i in indices],[[esc(q['population']),esc(label(q['method'])),q['role']]+[str(int(q[i])) for i in indices] for q in pivot.to_dict('records')],'Complete unique final population/method/role directed counts. Every seed has these exact counts, verified against each per-fit record. Zero and two-edge support remain explicit. Both synchronized relation panels use the same populations.',['tables/final_relation_counts.csv'],pivot,align=r'p{.11\textwidth}p{.18\textwidth}lrrrr',long=True)

full('appendix_partition_mapping','tables/fit_partition_mapping.csv',['fit','partition'],['Fit','Training partition'],'Every fit-to-training-partition link; partition feature counts and complete protected membership are given above.',align='lp{.55\\textwidth}')
failed=read('tables/failed_fits.csv');emit('appendix_failures',['Fit','Status','Failure'],[[fitids.get(q['name'],q['name']),esc(q['status']),esc(q['failure'])] for q in failed.to_dict('records')] or [['None','No failed core fit','All planned finite outcomes retained']], 'Actual core-fit failures. Separate preflight, authoring and published-dependency failures remain in the executed-command audit.',['tables/failed_fits.csv'],failed,align='lp{.20\\textwidth}p{.60\\textwidth}',long=True)
env=json.loads((RUN/'environment.json').read_text());envrows=[['Python',env['python']],['Platform',esc(env['platform'])]]+[[esc(k),esc(v)] for k,v in env['packages'].items()]+[['GPU0','NVIDIA TITAN RTX; 24 GiB'],['Driver','580.126.20'],['Tectonic','0.15.0']];emit('appendix_environment',['Component','Recorded value'],envrows,'Core environment for executed work; optional document/source helpers are isolated target installations. No exact published-model fit used these environment records.',['environment.json'],align='p{.20\\textwidth}p{.70\\textwidth}',long=True)
snapshot=RUN/'manuscript_inputs/commands_at_table_generation.jsonl';snapshot.parent.mkdir(exist_ok=True);shutil.copy2(RUN/'commands.jsonl',snapshot);cmds=readlines(snapshot);emit('appendix_commands',['Stage','Actual child command','Exit','Wall s'],[[esc(q['stage']).replace(r'\_',r'\_\allowbreak{}'),r'\texttt{'+esc(q['command'].replace(str(ROOT),'${PROJECT}')).replace(r'\_',r'\_\allowbreak{}').replace('/',r'/\allowbreak{}')+'}',str(q['exit_code']),num(q['wall_s'],3)] for q in cmds],'Executed stage commands available at table generation; the local project prefix is replaced by PROJECT for anonymous typesetting. Full delivery command logs include later manuscript/build/verification administration. Failed preflight attempts are retained.',['manuscript_inputs/commands_at_table_generation.jsonl'],align='p{.14\\textwidth}p{.57\\textwidth}rr',long=True)
source_records=[]
for pp in sorted((RUN/'sources').glob('*.record.json')):
 qq=json.loads(pp.read_text());source_records.append(dict(path=str(pp.relative_to(RUN)),wall_s=qq.get('wall_s'),child_cpu_s=qq.get('child_cpu_s'),exit_code=qq.get('exit_code'),error=qq.get('error')))
for pp in [RUN/'sources/primary_acquisition.json',RUN/'sources/megmod_attempt.json',RUN/'sources/citations/acquisition_manifest.json']:
 for i,qq in enumerate(json.loads(pp.read_text())):source_records.append(dict(path=str(pp.relative_to(RUN)),row=i,wall_s=qq.get('wall_s'),child_cpu_s=qq.get('child_cpu_s'),exit_code=qq.get('exit_code'),error=qq.get('error')))
sourcecost=dict(recorded_wall_s=sum(q['wall_s'] for q in source_records if q['wall_s'] is not None),recorded_child_cpu_s=sum(q['child_cpu_s'] for q in source_records if q['child_cpu_s'] is not None),recorded_errors=sum(q['error'] is not None for q in source_records),records=source_records,scope='Source/dependency/citation operations executed outside core fitting stages. Known metered subset; missing CPU fields are unmetered, not free. Original execution may overlap training wall time. Cached source-stage registration does not reexecute them.')
write(RUN/'source_administrative_accounting.json',sourcecost)
authoring=[json.loads(p.read_text()) for p in sorted((RUN/'authoring_attempts').glob('*.json'))];write(RUN/'manuscript_inputs/authoring_at_table_generation.json',authoring)
resource_rows=[['Core fit objects',str(len(fit))],['Executed optimizer updates',str(int(fit.executed_updates.sum()))],['Selected-checkpoint updates',str(int(fit.selected_updates.sum()))],['Summed core-fit CPU seconds',num(fit.cpu_s.sum(),3)],['Summed core-fit wall seconds',num(fit.wall_s.sum(),3)],['GPU training-region elapsed seconds',num(fit.gpu_region_wall_s.sum(),3)],['Completed stage child CPU seconds',num(sum(q['child_cpu_s'] for q in cmds),3)],['Completed stage aggregate wall seconds',num(sum(q['wall_s'] for q in cmds),3)],['Maximum reported stage child RSS, KiB',str(max(q['max_child_rss_kib'] for q in cmds))],['Recorded source/dependency/citation wall seconds',num(sourcecost['recorded_wall_s'],3)],['Recorded source-command child CPU seconds',num(sourcecost['recorded_child_cpu_s'],3)],['Recorded manuscript-authoring wall seconds',num(sum(q['wall_s'] for q in authoring),3)],['Recorded manuscript-authoring child CPU seconds',num(sum(q['child_cpu_s'] for q in authoring),3)],['Exact published predictors fitted','0'],['Administrative inspection/authoring','Additional unmetered nonzero cost']];emit('appendix_resources',['Quantity and scope','Actual value'],resource_rows,'Actual cost through completed pre-manuscript stages; fit-region and stage costs overlap and are not added. Full delivery audit records later administration. No historical ledger was consumed.',['tables/all_fit_summary.csv','manuscript_inputs/commands_at_table_generation.jsonl','source_administrative_accounting.json','manuscript_inputs/authoring_at_table_generation.json'],align='p{.62\\textwidth}p{.28\\textwidth}',long=True)
# Historical values come from the newly executed legacy recomputation, never copied from review prose.
lm=read('legacy/activity_metrics.csv') if (RUN/'legacy/activity_metrics.csv').exists() else pd.DataFrame()
history=[['Empirical v1','Three-seed small-validation campaign','Preserved; initial GNN/tree and bundle-effect negatives remain historical results'],['Empirical v2 / manuscript v5','Retrospective support/context and pair follow-up','Preserved with its complete logs; superseded tables are not mixed with current fits'],['Empirical v3 / manuscript v6','Frozen grouped selection; ten final seeds','Current controlled procedures and primary B3 source check'],['Separate mathematical manuscript','Five-law recovery and lower-bound study','Preserved separately; no theorem coverage or new backend claimed']];emit('appendix_history',['Version','Protocol','Role in this paper'],history,'Version history and preservation scope. Historical empirical recomputation is retained under legacy/ with exact constants and seed/ensemble distinctions.',['legacy_analysis.done.json','protocol.json'],align='p{.23\\textwidth}p{.28\\textwidth}p{.39\\textwidth}',long=True)


hist=read('tables/historical_v1_results.csv');body=[]
for c,est,ms in [('test_APP','activity',['gnn','chemistry_tree','nongraph']),('test_internal','activity',['gnn','chemistry_tree','nongraph']),('APP_B2','measured_bundle_difference',['gnn','chemistry_tree','guide_ridge'])]:
 for m in ms:
  z=hist[(hist.cohort==c)&(hist.method==m)&(hist.estimand==est)].iloc[0];body.append(['v1 frozen',esc(c),esc(m),num(z.mse,6)])
la=read('legacy/activity_metrics.csv')
for pr,c in [('v2_deployment_all_ENsi_inner_selected','test_APP'),('v2_deployment','Davis_S7')]:
 for m in ['gnn','nongraph','chemistry_tree','token_cnn','training_row_mean','training_equal_study_mean','oracle_test_mean_diagnostic']:
  z=la[(la.protocol==pr)&(la.cohort==c)&(la.model==m)&(la.weighting=='rows')].iloc[0];body.append(['v2 deployment',esc(c),esc(m).replace(r'\_',r'\_\allowbreak{}'),num(z.mse,6)])
emit('appendix_historical_results',['Version','Cohort/estimand','Method','MSE'],body,'Compact preserved historical results. V1 APP B2 is frozen activity prediction, not the new supervised pair experiment. V2 deployment and S7 are kept distinct. The original GNN/tree and bundle-effect negative outcomes remain visible.',['tables/historical_v1_results.csv','legacy/activity_metrics.csv'],align='lp{.22\\textwidth}p{.40\\textwidth}r',long=True)
se=read('legacy/seed_metrics.csv');q=se[(se.protocol=='v2_factorial_R1C1')&(se.cohort=='test_APP')&(se.model=='gnn')];emit('appendix_review_seed_correction',['Historical arm','Seed','Exact MSE'],[['v2 factorial R1C1',esc(z.seed),num(z.mse,6)] for z in q.itertuples()],'The three listed member errors all exceed the review reference 0.1627. The ensemble error is a different statistic. These are neither v2 deployment seeds nor the new ten-seed campaign.',['legacy/seed_metrics.csv'],q,align='lrr',long=True)


full('appendix_B2_within_assay','tables/B2_within_assay_variation.csv',['method','correlation','prediction_sd','label_sd','conditional_correlation_lower','conditional_correlation_upper'],['Method','Within-assay $r$',r'\shortstack{Pred.\\SD}',r'\shortstack{Label\\SD}','Lower','Upper'],'Labeled within-assay variation diagnostic. Both means are removed inside each sequence-component resample; this uses evaluation labels only for analysis and is not a deployable centering correction or a new fit.',fmt={c:5 for c in ['correlation','prediction_sd','label_sd','conditional_correlation_lower','conditional_correlation_upper']},align='p{.23\\textwidth}rrrrr')
full('appendix_pair_spread','tables/pair_metrics.csv',['method','weighting','r_squared','label_sd','label_mean','prediction_mean'],['Method','Weights','$R^2$',r'\shortstack{Label\\SD}','Label mean','Pred. mean'],'Remaining B2 regression diagnostics on the original difference scale; majority direction has no regression interpretation.',fmt={c:5 for c in ['r_squared','label_sd','label_mean','prediction_mean']},align='p{.23\\textwidth}p{.16\\textwidth}rrrr')


full('appendix_fold_spread','tables/per_fold_seed_metrics.csv',['cohort','population','method','seed','mae','r_squared','prediction_sd','label_sd'],['Cohort','Outer','Method','Seed','MAE','$R^2$',r'\shortstack{Pred.\\SD}',r'\shortstack{Label\\SD}'],'Remaining diagnostics for every held-out fold and seed; corresponding MSE, correlation and bias in the preceding fold table.',fmt={c:5 for c in ['mae','r_squared','prediction_sd','label_sd']},align=r'p{.11\textwidth}p{.09\textwidth}p{.16\textwidth}rrrrr')
full('appendix_pair_seed_spread','tables/pair_seed_metrics.csv',['method','seed','weighting','mae','r_squared','label_sd'],['Method','Seed','Weights','MAE','$R^2$',r'\shortstack{Label\\SD}'],'Remaining diagnostics for every B2 final seed and weighting.',fmt={c:5 for c in ['mae','r_squared','label_sd']},align=r'p{.23\textwidth}rp{.16\textwidth}rrr')
full('appendix_pair_endpoint_spread','tables/pair_endpoint_metrics.csv',['method','seed','r_squared','label_sd','label_mean','prediction_mean'],['Endpoint method','Seed','$R^2$',r'\shortstack{Label\\SD}','Label mean','Pred. mean'],'Remaining endpoint diagnostics; direct pair-only ridge/tree do not produce endpoint activities.',fmt={c:5 for c in ['r_squared','label_sd','label_mean','prediction_mean']},align=r'p{.25\textwidth}rrrrr')
full('appendix_B3_spread','tables/b3_metrics.csv',['method','seed','r_squared','label_sd','label_mean','prediction_mean'],['B3 method','Seed','$R^2$',r'\shortstack{Label\\SD}','Label mean','Pred. mean'],'Remaining B3 diagnostics for every member and ensemble; shared-background dependence precludes an independent-rectangle interval.',fmt={c:5 for c in ['r_squared','label_sd','label_mean','prediction_mean']},align=r'p{.25\textwidth}rrrrr')
full('appendix_assay_groups','tables/per_assay_metrics.csv',['cohort','method','assay','n','sequence_components','study_linked_groups','source_families'],['Cohort','Method','Assay','$n$','Seq.','Study','Source'],'Actual grouping counts behind every per-assay result; study-linked groups and source families are not certified independent biological studies.',align=r'p{.10\textwidth}p{.18\textwidth}p{.26\textwidth}rrrr')


full('appendix_training_identity','tables/matched_support_training_identity.csv',['original_fit','seed','same_selected_configuration','same_selected_epoch','same_executed_updates','validation_prediction_max_absolute_difference','selected_parameter_max_absolute_difference','selected_parameters_bit_identical'],['R0 fit','Seed','Config.',r'\shortstack{Best\\epoch}',r'\shortstack{Run\\updates}',r'\shortstack{Val.\\max $|d|$}',r'\shortstack{Weight\\max $|d|$}','Identical'],'Every original/corrected final matched-seed training comparison, where the fit ID identifies its population and graph/no-message arm; the counterpart replaces R0 by R1 with the same seed. These checks use saved tensors/predictions, not new fitting. Inference routing may differ even when selected tensors are identical.',fmt={'validation_prediction_max_absolute_difference':'.2e','selected_parameter_max_absolute_difference':'.2e'},align='lrllllll')


full('appendix_realized_parameter_activity','tables/selected_parameter_activity_summary.csv',['fit','parameters','selected_activity_gradient_nonzero_scalars','selected_training_objective_nonzero_scalars','changed_from_initialized_scalars','selected_training_objective_gradient_norm'],['Fit','Owned',r'\shortstack{Data\\activity}',r'\shortstack{Data\\objective}','Changed',r'\shortstack{Objective\\norm}'],'Every completed final neural checkpoint: realized nonzero-gradient scalar counts under activity loss and the actual training objective, dropout disabled. The latter adds the selected pair term for pair-trained rows. Changed scalars include weight decay. These are selected-checkpoint counts, not a claim that every other scalar never learned during the trajectory. All tensor-level values accompany the summary CSV.',fmt={'selected_training_objective_gradient_norm':'.3e'},align='lrrrrr')


# Every pair outer fold is reported separately from the pooled OOF result.
for suffix,cols,headers in [
 ('errors',['n','mse','mae','correlation'],['$n$','MSE','MAE','$r$']),
 ('spread',['r_squared','prediction_sd','label_sd','mean_bias'],['$R^2$',r'\shortstack{Pred.\\SD}',r'\shortstack{Label\\SD}','Bias']),
 ('signs',['sign_accuracy','non_tie_correct','non_ties'],['Acc.','Correct',r'\shortstack{Non-\\ties}']),
 ('calls',['negative_calls','zero_calls','positive_calls'],['Neg.','Zero','Pos.']),
 ('groups',['sequence_components','exact_backgrounds'],['Seq.','Backgrounds'])]:
 full('appendix_B2_fold_'+suffix,'tables/B2_fold_seed_metrics.csv',['population','method','seed','weighting']+cols,['Outer','Method','Seed','Weights']+headers,'Complete held-out B2 fold, method, seed and ensemble diagnostics; the synchronized panels use identical rows and their named weights. Finite unfavorable seeds remain; majority is direction-only.',fmt={c:5 for c in cols if c in ['mse','mae','correlation','r_squared','prediction_sd','label_sd','mean_bias','sign_accuracy']},align=r'p{.09\textwidth}p{.18\textwidth}rp{.11\textwidth}'+('r'*len(cols)))
for suffix,cols,headers in [
 ('errors',['n','mse','mae','correlation'],['$n$','MSE','MAE','$r$']),
 ('spread',['r_squared','prediction_sd','label_sd','mean_bias'],['$R^2$',r'\shortstack{Pred.\\SD}',r'\shortstack{Label\\SD}','Bias'])]:
 full('appendix_B2_endpoint_fold_'+suffix,'tables/B2_endpoint_fold_metrics.csv',['population','method','seed']+cols,['Outer','Method','Seed']+headers,'Every neural endpoint activity result within each protected B2 outer fold and seed, plus ensembles. Metrics give equal weight to sequence components within that fold.',fmt={c:5 for c in cols if c!='n'},align=r'p{.13\textwidth}p{.23\textwidth}r'+('r'*len(cols)))
full('appendix_B2_duplexes','tables/B2_duplex_states.csv',['duplex','guide_sequence','passenger_sequence','guide_chemistry','passenger_chemistry'],['Duplex','Guide bases','Passenger bases','Guide C','Pass. C'],'Closed dictionary of every distinct measured B2 duplex input. Both strands retain printed 5-prime to 3-prime order; C codes expand to the full positional/linkage chemistry in the following tables.',align=r'lp{.30\textwidth}p{.30\textwidth}ll')
full('appendix_B2_chemistry','tables/B2_chemistry_templates.csv',['template','length','positional_chemistry'],['C','Length','Complete positional chemistry'],'Every B2 strand chemistry template. Each one-based nucleotide position explicitly lists its modification-name set. Stereochemistry is unreported unless shown in brackets; absence of a reported stereo label is not a stereochemical assignment.',align=r'lrp{.75\textwidth}')
full('appendix_B2_linkages','tables/B2_chemistry_templates.csv',['template','linkages','terminals'],['C','Complete directed within-strand links','Terminal entries'],'Linkage and terminal complement to the positional B2 template table. i-j denotes the bond from one-based position i to j in printed strand order. Empty brackets mean an empty parsed terminal list.',align=r'lp{.61\textwidth}p{.24\textwidth}')
# The exact assay is represented by its already printed closed APP pool mapping.
pm=read('tables/B2_measured_endpoint_mapping.csv');emit('appendix_B2_endpoint_mapping',['Pair','Ref. D','Changed D','Pool','$y_{ref}$','$y_{changed}$'],[[r'\texttt{\seqsplit{'+esc(q.pair_id)+'}}',q.reference_duplex,q.changed_duplex,poolids[q.assay_id],num(q.reference_activity,6),num(q.changed_activity,6)] for q in pm.itertuples()],'Every B2 pair mapped to its two duplex inputs, exact assay pool and measured endpoint activities. The preceding identity table supplies original record IDs and endpoint SDs; the APP pool dictionary supplies the complete assay string. Difference orientation is changed minus reference.',['tables/B2_measured_endpoint_mapping.csv','tables/ranking_direct_pool_differences.csv'],pm,align=r'p{.20\textwidth}lllrr',long=True)

# Save summary and all machine-readable provenance rather than hand-copying outcomes.
write(RUN/'table_provenance.json',maps);write(RUN/'paper_result_claims.json',dict(APP_gnn_vs_tree=dict(app),APP_gnn_vs_no_message=dict(nm),B2_gnn_vs_training_mean=dict(pairmean),APP_strongest_observed_baseline=bestname,APP_gnn_vs_strongest_observed=dict(bestcontrast),conditional_APP_advantage_strongest_observed=bool(positive),B2_sequence_variation_improvement=bool(pairpositive),all_core_fits=len(fit),published_exact_fits=0,source_B3=b3sum))
print('Generated',len(maps),'tables and all numeric prose')
