"""Finish bounded primary-evidence audit; no scientific fitting."""
from common import *
import re,xml.etree.ElementTree as E,subprocess
s=RUN/'sources';root=E.parse(s/'PMC12205987.xml').getroot();paras=[''.join(n.itertext()) for n in root.iter('p')];checks=[p for p in paras if any(x in p.lower() for x in ['antisense','table s1','sense strand','reverse complement','supplementary table s7'])]
(s/'davis_primary_orientation_excerpts.txt').write_text('\n\n'.join(checks))
q=pd.read_csv(PREV/'source_audit/davis_orientation_rows.csv');export(q,'sources/davis_S1_orientation_rows_preserved.csv')
write(s/'S1_status.json',dict(status='ACQUIRED_BUT_ORIENTATION_UNRESOLVED',workbook=str((PREV/'source_audit/davis_original_supplement.xlsx').relative_to(ROOT)),workbook_sha256=sha(PREV/'source_audit/davis_original_supplement.xlsx'),current_primary_xml_sha256=sha(s/'PMC12205987.xml'),checks=['Printed S1 header and first chemical strings inspected','Full primary XML searched for strand orientation, reverse complement and S1 descriptions','Primary method reverse-complement statement concerns RNA-seq reads, not conversion of chemical scaffold strings','Current Crossref metadata has no linked correction resolving S1 orientation','Retained all 1248 historical row-level orientation checks'],conclusion='No authoritative conversion of the printed target-sense antisense strings was found. No strand/base/chemical-position reversal is guessed. This does not invalidate the biological experiments.',new_admitted_S1_rows=0))
b=pd.read_csv(RUN/'b3/primary_reconciliation.csv');v=b[b.absolute_difference.notna()];write(s/'primary_release_discrepancies.json',dict(identity_matched_pairs=len(v),within_half_tenth_percentage_point=int((v.absolute_difference<=.000500001).sum()),within_half_percentage_point=int((v.absolute_difference<=.005000001).sum()),greater_than_five_percentage_points=int((v.absolute_difference>.05).sum()),max_absolute_activity_difference=float(v.absolute_difference.max()),interpretation='Identity-based primary/released discrepancies, conditional on the documented chemistry mapping. Some small differences can reflect coarser release rounding; large differences require source reconciliation. Frozen benchmark labels are not overwritten. This is not a claim that every mismatch is a biological measurement error.'))
repo=ROOT/'handoffs/codex_revision_v1/MEG_mod_official';files=list(repo.rglob('*.py'));names=['s_tokens','a_tokens','max_L_mod_sense','max_L_mod_anti','embed_dim'];hits=[]
for p in files:
 for no,line in enumerate(p.read_text().splitlines(),1):
  if any(re.search(r'\b'+n+r'\b',line) for n in names):hits.append(dict(file=str(p.relative_to(repo)),line=no,text=line))
write(s/'megmod_unresolved_forward_symbols.json',hits)
write(s/'reproduction_status.json',dict(ENsiRNA_mod=dict(status='BLOCKED_EXACT_REPRODUCTION',commit='028824341635903f3c661f5d1cc737de106493d5',attempts=['install_dependencies.record.json','acquire_official_pdb.record.json','official_preprocess_help.record.json','rosetta_probe.record.json'],blocker='Public official PDB download failed; configured Rosetta geometry generator is absent. RNA-FM representation is cached but does not supply missing per-duplex geometry.',exact_supervised_fits=0,supervised_efficacy_checkpoint_used=False),MEG_mod=dict(status='BLOCKED_EXACT_REPRODUCTION',commit='c335a4c69d56ef73754677da8bfe627c8112b350',attempts=['megmod_attempt.json','megmod_training_entrypoint.log','megmod_unresolved_forward_symbols.json'],blocker='Released BAN_graph.py fails at import with missing torch; the forward pass additionally references undeclared strand token tensors/dimensions without their constructing code. Fixing imports alone does not specify that scientific representation.',available_assets=['unimol_1b_emb_dict.pkl','cofold_results.pkl'],RNAErnie_base_asset='Public listed 1.018GB asset not downloaded because missing forward representation already prevents exact reproduction; not declared inaccessible.',exact_supervised_fits=0,supervised_efficacy_checkpoint_used=False),reserved_fit_budget=100,executed_exact_published_fits=0,approximation_substituted=False))
print(json.dumps(json.loads((s/'primary_release_discrepancies.json').read_text()),indent=2))
