from core import *
import re
P=ROOT/'papers/interaction_recoverability_iclr2027/v3';out=P/'sections'
def esc(s):
 if s is None or (isinstance(s,float) and not np.isfinite(s)):return '--'
 return str(s).replace('\\',r'\textbackslash{}').replace('&',r'\&').replace('%',r'\%').replace('_',r'\_').replace('#',r'\#')
def n(x):return '--' if pd.isna(x) else f'{float(x):.4f}'
def table(file,headers,rows,caption,label,widths=None):
 spec=widths or ('l'+'r'*(len(headers)-1));s='\\begin{table}[h]\\centering\n\\begin{tabular}{'+spec+'}\\toprule\n'+' & '.join(headers)+r'\\\midrule'+'\n'
 s+=''.join(' & '.join(str(v) for v in row)+r'\\'+'\n' for row in rows);s+='\\bottomrule\\end{tabular}\n\\caption{'+caption+'}\\label{'+label+'}\n\\end{table}\n';(out/file).write_text(s)
names={'gnn':'GNN','chemistry_tree':'Chemistry tree','token_cnn':'Token CNN','nongraph':'No-message','gnn_no_chemistry':'No chemistry','context_ridge':'Context ridge','mean_unweighted':'Row mean','mean_equal_study':'Study mean','gnn_activity':'Activity GNN','gnn_pair':'Pair GNN','nongraph_pair':'Pair no-message','training_mean':'Fold mean','training_majority':'Fold majority','pair_ridge':'Pair ridge','zero':'Zero'}
b=pd.read_csv(RUN/'B1_comparison.csv');b=b[b.seed=='ensemble'];f=pd.read_csv(RUN/'all_fit_summary.csv');ef=pd.read_csv(RUN/'external_comparison.csv');ef=ef[ef.seed=='ensemble']
original=[['GNN','.060432','.174726','.521442','.292107'],['Chemistry tree','.051757','.168597','.564846','.281246'],['Token CNN','.056367','.186286','.452873','.284191'],['No-message','.056301','.195609','.497116','.283509'],['Pairwise ridge','.065838','.208019','.434037','.280804'],['Guide ridge','.071228','.301295','.518567','.280804'],['No chemistry (old)','.066582','.207189','.654656','.280804']]
table('table_original.tex',['Original model','Internal','APP','Top five','B2'],original,'Frozen v1 results, unchanged. Internal/APP/B2 columns are MSE (lower better); top five is mean selected percentile (higher better) across 17 related APP pools. Counts: 198 internal observations, 1,839 APP observations, 156 pairs. Neural/tree rows average three seeds; ridges use one fit.','tab:original')
table('table_support.tex',['Directed relation','Train','APP'],[['PO backbone','0','132,012'],['PS backbone','0','22,464'],['Unresolved backbone','215,050','0'],['Canonical pairing','100,472','77,238'],['Mismatched pairing','2','0']],'Archived graph support, combining forward/reverse edges. Counts describe graph tensors, not biological bonds measured experimentally. All four resolved PO/PS relation matrices have zero training-data gradient in both layers.','tab:support')
q=b[(b.phase=='frozen')&(b.model=='gnn')];order=['original','backbone','zero_support','combined'];q=q.set_index('arm').loc[order]
table('table_frozen.tex',['Frozen GNN input','Internal','APP','Top five','B2'],[[a.replace('_',' ').title()]+[n(x[k]) for k in ['internal_mse','APP_mse','APP_top5_percentile','B2_pair_mse']] for a,x in q.iterrows()],'Modified inference on the same three v1 checkpoints; no fitting. MSE columns lower better, percentile higher better. Original populations and pair orientation are unchanged. All APP arms are retrospective diagnostics.','tab:frozen')
q=b[b.phase=='factorial'];order=[('gnn',a) for a in ['R0C0','R1C0','R0C1','R1C1']]+[(m,'R1C1') for m in ['chemistry_tree','token_cnn','nongraph','gnn_no_chemistry','context_ridge','mean_unweighted','mean_equal_study']];rr=[]
for kind,arm in order:
 x=q[(q.model==kind)&(q.arm==arm)].iloc[0];rr.append([names[kind]+(' '+arm if kind=='gnn' else '')]+[n(x[k]) for k in ['internal_mse','APP_mse','APP_top5_percentile','B2_pair_mse']])
# Constant-ranking artifacts are printed in the appendix, not represented as learned selection.
for row in rr:
 if row[0] in ['Context ridge','Row mean','Study mean']:row[3]='--'
table('table_refits.tex',['New original-split fit','Internal','APP','Top five','B2'],rr,'Prespecified refits, original split; 198 internal, 1,839 APP and 156 B2 observations/pairs. R/C denote supported representation/context. Three-seed stochastic ensembles; context ridge and training means are deterministic. MSE lower and percentile higher are better. Constant-predictor tie scores are not ranking utility. All APP results are retrospective.','tab:refits')
q=b[b.phase=='deployment'];table('table_ranking.tex',['Inner-selected model','APP MSE','Assay $\\rho$','Top five','Activity'],[[names[x.model],n(x.APP_mse),n(x.APP_equal_assay_rho),n(x.APP_top5_percentile),n(x.APP_selected_activity)] for x in q.itertuples()],'All-ENsiRNA three-seed ensembles on 1,839 APP records in 17 common pools. MSE lower is better; Spearman, percentile and selected measured inhibition higher are better. Pool averages are equal-weighted and retrospective; activity is not a causal or clinical benefit estimate.','tab:ranking')
g=pd.read_csv(RUN/'grouped_comparison.csv');g=g[g.seed=='ensemble'];table('table_grouped.tex',['Model','Pooled MSE','Study MSE','Fold MSE','MAE'],[[names[x.model],n(x.pooled_mse),n(x.equal_component_mse),n(x.equal_fold_mse),n(x.mae)] for x in g.itertuples()],'Retrospective nested grouped evaluation of all 2,927 ENsiRNA observations, ten study-linked components and five outer folds. Predictions are three-seed ensembles. Columns use pooled rows, equal study components, equal folds and pooled absolute error; all lower is better. Components are not certified independent laboratories.','tab:grouped')
bb=pd.read_csv(RUN/'B2_supervised_comparison.csv');bb=bb[bb.seed=='ensemble'];order=['zero','training_mean','training_majority','pair_ridge','gnn_activity','gnn_pair','nongraph_pair'];bb=bb.set_index('model').loc[order]
table('table_b2.tex',['Method','Pair MSE','Group MSE','MAE','Calls','Correct'],[[names[k],n(x.pair_mse),n(x.equal_component_mse),n(x.pair_mae),str(int(x.calls))+'/137',str(int(x.correct_calls))+'/'+str(int(x.calls)) if x.calls else '--'] for k,x in bb.iterrows()],'Exploratory APP supervision: 156 pairs, 12 sequence components, four outer folds. Lower errors are better. Calls and correctness are on measured non-ties; zero abstains. Fold majority is a classifier, without a magnitude MSE. Neural predictions average three seeds. The fixed band is $\\pm.02$.','tab:b2')
table('table_external.tex',['Frozen deployment model','MSE','MAE','Group MSE'],[[names[x.model],n(x.mse),n(x.mae),n(x.equal_component_mse)] for x in ef.itertuples()],'Davis S7: 118 separately sourced measured native-expression outcomes in 76 sequence components. Three-seed predictions use fixed ENsiRNA-trained checkpoints. Lower is better; group MSE weights sequence components equally. Dose/time remain masked. This is observational assessment, not prospective or wet-lab validation.','tab:external')
q=f[(f.kind=='gnn')&(f.tag=='factorial/final/R1C1')];table('table_epochs.tex',['Corrected GNN seed','Best epoch','Best updates','All updates'],[[str(x.seed),str(x.selected_epoch),str(x.selected_updates),str(x.optimizer_updates)] for x in q.itertuples()],'Every corrected original-split GNN seed. Checkpoints are chosen by the original validation groups; executed and selected-state update counts differ. No APP outcome selected a seed or epoch. Full fold/configuration histories are supplied in the appendix and artifacts.','tab:epochs')
# Longtable helper: caption appears after the final segment, never at the top.
def longtable(path,df,caption,label,formats=None):
 cols=list(df.columns);formats=formats or ['p{'+str(round(.92/len(cols),3))+r'\textwidth}']*len(cols);s='\\begin{longtable}{'+''.join(formats)+'}\n\\toprule\n'+' & '.join(esc(c) for c in cols)+r'\\\midrule\endfirsthead'+'\n\\toprule\n'+' & '.join(esc(c) for c in cols)+r'\\\midrule\endhead'+'\n'
 for row in df.itertuples(index=False,name=None):s+=' & '.join(n(v) if isinstance(v,(float,np.floating)) else esc(v) for v in row)+r'\\'+'\n'
 s+='\\bottomrule\n\\caption{'+caption+'}\\label{'+label+r'}\\'+'\n\\end{longtable}\n';path.write_text(s)
app=P/'appendices';tables=[]
def add(name,df,caption):
 longtable(app/(name+'.tex'),df,caption,'app:table:'+name);tables.append(name)
# Every model/arm/seed endpoint, split over narrow tables to preserve normal font size.
allb=pd.read_csv(RUN/'B1_comparison.csv');allb['ID']=[f'B{i+1}' for i in range(len(allb))];add('all_B1_identity',allb[['ID','phase','model','arm','seed']],'Identity key for every frozen/refit/deployment model, arm and individual seed or equal-seed ensemble. All APP evaluations are retrospective.')
add('all_B1_errors',allb[['ID','internal_mse','APP_mse','APP_equal_assay_rho','B2_pair_mse','B2_equal_component_mse']],'Complete error and association endpoints for the identities above. MSE lower, correlation higher are better. B2 uses 156 original transfer pairs; this table does not use within-APP supervised fits.')
add('all_B1_ranking',allb[['ID','APP_top5_percentile','APP_selected_activity','parameters_each','selected_epochs','executed_updates','selected_updates']],'Complete ranking and fitting account for every B1 identity. Counts for frozen arms describe their shared archived checkpoints, not new updates. Tree parameter counts are tree nodes and are not comparable to neural scalar counts. Constant ID-tie rankings are artifacts; random-tie expectations are separately tabulated.')
f['ID']=[f'F{i+1}' for i in range(len(f))];add('all_fits_identity',f[['ID','tag','kind','seed']],'Every completed engine fit. Development fits use seed 701; final stochastic fits use the same three seeds. The four direct pair-ridge fits are specified separately; they have no neural updates.')
f['configuration']=f.config.map(lambda s:eval(s,{'__builtins__':{}},{})['name']);add('all_fits_settings',f[['ID','configuration','lambda_pair','training_n','validation_n','test_n']],'Full fit configuration, pair-loss weight and population sizes. Two fixed neural configurations and two fixed tree leaf sizes are the complete selection grids. Empty test populations identify development-only fits.')
add('all_fits_counts',f[['ID','parameters','selected_epoch','epochs_executed','selected_updates','optimizer_updates','validation_score']],'Selected and executed epochs/updates and inner-validation objective for every fit. Tree parameters count nodes. B2 validation objective is equal-component pair MSE; other selected objectives are equal-study activity MSE.')
g=pd.read_csv(RUN/'grouped_component_results.csv');add('all_outer_results',g[['model','seed','outer_fold','study_group','n','mse','mae']],'Every outer component and seed, including three-seed ensembles. All ten components are evaluated once; pooled and equal-weight summaries are not interchangeable.')
member=pd.read_csv(RUN/'grouped_membership.csv');groups=member.groupby(['outer_fold','role','study_group'],as_index=False).agg(n=('record_id','size'),sources=('source_family',lambda x:'; '.join(sorted(set(x)))));add('group_membership',groups,'Exact grouped outer/inner membership and source labels. Hash-based group selection uses no outcomes. Full record IDs are preserved in the companion clean-input archive.')
for name,file,cols,cap in [('supervised_b2_all','B2_supervised_comparison.csv',['model','seed','pair_mse','equal_component_mse','pair_mae','equal_component_mae'],'Every supervised B2 model and seed. All errors describe outer-test pairs; group errors weight 12 sequence components equally.'),('supervised_b2_direction','B2_supervised_comparison.csv',['model','seed','mean_predicted','predicted_min','predicted_max','calls','correct_calls'],'Predicted magnitude and direction-call counts, with the unchanged operational band. Majority predictions are direction labels, not quantitative effect predictions.'),('supervised_b2_folds','B2_fold_results.csv',['model','seed','outer_fold','n','pair_mse','equal_component_mse'],'All outer-fold B2 error results, including every unfavorable fold.'),('all_paired_intervals','paired_comparisons.csv',['phase','model','difference_mse','lower95','upper95'],'Conditional paired bootstrap comparisons: references are the corrected tree for factorial/deployment and grouped evaluations, and fold mean for B2. No multiple-comparison or new-study coverage claim.'),('external_all','external_comparison.csv',None,'All Davis S7 models and seeds. Public native-outcome measurements, source-specific structural admission and frozen ENsiRNA deployment checkpoints.'),('external_targets','external_target_results.csv',None,'All Davis S7 target/cell groups and seeds. Source-provided target labels, including human/mouse naming inconsistencies, are retained literally and are not neural inputs.')]:
 d=pd.read_csv(RUN/file);add(name,d if cols is None else d[cols],cap)
r=pd.read_csv(RUN/'ranking_by_assay.csv');r=r[r.seed=='ensemble'].copy();poolids={a:'A'+str(i+1) for i,a in enumerate(sorted(r.assay_id.unique()))};add('pool_identity',pd.DataFrame([dict(pool=v,primary_assay=k) for k,v in poolids.items()]),'Exact APP pool key. All pools are related patent-family evidence; doses, cells and tables do not become independent studies.');r.assay_id=r.assay_id.map(poolids);add('all_ranking_pools',r[['phase','model','arm','assay_id','n','spearman','top5_percentile','selected_activity']],'All ensemble ranking endpoints for every common APP pool. Higher percentile and selected inhibition are better, but no clinical or causal interpretation follows.')
t=pd.read_csv(RUN/'ranking_tie_expectations.csv');t=t.groupby(['phase','model','arm'],as_index=False)[['expected_top5_percentile','expected_selected_activity']].mean();add('tie_expectations',t,'Exact expectation when the last selected prediction tie is broken uniformly, supplementary to the unchanged deterministic ID rule. Constant predictors have expected percentile 0.5; an ID-order value is not learned selection.')
add('full_relation_support',pd.read_csv(RUN/'relation_support.csv'),'All eight directed relation support counts for each archived split. No synthetic graph values are substituted.')
add('full_context_support',pd.read_csv(RUN/'context_support.csv').drop(columns='name'),'Minimum/maximum standardized coordinates for every archived split and whether the training coordinate is identically zero. Coordinate definitions are reproduced below.')
add('full_gradients',pd.read_csv(RUN/'data_gradients.csv'),'Full training-data gradient L2 norms for every relation matrix, embedding column and context column in each archived GNN seed. No optimizer update or weight decay is included in this diagnostic.')
(P/'appendices/table_manifest.json').write_text(json.dumps(tables,indent=2));print('tables',len(tables),'fits',len(f))
