"""Final non-circular delivery receipt; run after archive packaging and resume check."""
from common import *
import subprocess
rows=[json.loads(l) for l in (RUN/'commands.jsonl').read_text().splitlines()]
paths=[PAPER/'artifacts/main.pdf',PAPER/'artifacts/manuscript_source.zip',PAPER/'artifacts/typesetting_dependencies.zip',PAPER/'artifacts/figures/workflow.pdf',PAPER/'artifacts/figures/workflow.svg',RUN/'delivery/contribution_code_evidence.zip',ROOT/'review_packages/sirna_gnn_review_v4.zip']
record=dict(status='Completed applicable gated investigation; no novel learned method established',gates=json.loads((DOC/'gate_decision.json').read_text())['gates'],pages=json.loads((PAPER/'artifacts/page_boundaries.json').read_text()),new_fits=0,training_updates=0,correctness_cases=19,verified_parent_fit_artifacts=3564,artifacts=[dict(path=str(p.relative_to(ROOT)),bytes=p.stat().st_size,sha256=sha(p)) for p in paths],recorded_stage_wall_s=sum(r['wall_s'] for r in rows),recorded_stage_child_cpu_s=sum(r['child_cpu_s'] for r in rows),max_stage_rss_kib=max(r['max_rss_kib'] for r in rows),accounting='Includes repeated verification/build passes and package stage; excludes additional nonzero unmetered authoring/browsing/direct administrative commands; nested build receipts overlap, not additive',GPU_work=False,pushed=False,external_contact=False,archive_self_reference='Archive cannot include its final hash or final packaging cost. This receipt and original runner commands are supplied alongside.')
write(DOC/'delivery_manifest.json',record);write(RUN/'delivery/final_receipt.json',record)
(DOC/'WORK_STATE.md').write_text('# Completed checkpoint\n\nManuscript v10 and investigation v5 are final. G1 FAIL; G2 UNRESOLVED; G3 blocked. No new training fits. See delivery_manifest.json for verified artifacts, exact costs and page boundaries. The prior manuscripts/campaigns are untouched. Current source is exactly four entries. Full page render and independent ZIP compilation pass. No push or external contact.\n')
print(json.dumps({k:record[k] for k in ['status','pages','recorded_stage_wall_s','recorded_stage_child_cpu_s','new_fits']},indent=2))
