"""Delivery reports from completed fit/evaluation/build records."""
from common import *
import re,subprocess,shlex
D=ROOT/'docs/sirna_gnn_empirical/v4';D.mkdir(exist_ok=True);P=ROOT/'papers/interaction_recoverability_iclr2027/v9';A=P/'artifacts';S=P/'source';fit=json.loads((RUN/'fit_completion.json').read_text());metrics=pd.read_csv(RUN/'evaluation/activity_metrics.csv');direct=pd.read_csv(RUN/'evaluation/direct_comparisons.csv');bounds=json.loads((A/'page_boundaries.json').read_text());checks=json.loads((RUN/'audit/scientific_audit.json').read_text());names={'corrected_gnn':'GNN','corrected_no_message':'No-message','chemistry_tree':'Chemistry tree','token_cnn':'Token CNN'}
rr=[]
for s in ['source_excluded','primary_reanchored']:
 for m,label in names.items():
  q=metrics[(metrics.scenario==s)&(metrics.method==m)&(metrics.weighting=='rows')].set_index('cohort');rr.append([s,label]+[q.loc[c,'mse'] for c in ['ENsiRNA_grouped','APP','Davis_S7']])
table=pd.DataFrame(rr,columns=['Sensitivity','Method','Grouped MSE','APP MSE','S7 MSE']).to_markdown(index=False,floatfmt='.6f')
cmds=[]
for name in ['commands.jsonl','diagnostic_commands.jsonl']:
 if (RUN/name).exists():cmds+=readlines(RUN/name)
wall=sum(x['wall_s'] for x in cmds);cpu=sum(x['child_cpu_s'] for x in cmds);rss=max(x['max_rss_kib'] for x in cmds)
resource=dict(recorded_stage_and_diagnostic_wall_s=wall,recorded_stage_and_diagnostic_child_cpu_s=cpu,maximum_reported_child_rss_kib=rss,fit_cpu_s=fit['fit_cpu_s'],fit_wall_s=fit['fit_wall_s'],gpu_fitting_region_wall_s=fit['gpu_region_wall_s'],costs_overlap=True,administrative_cost='Additional nonzero direct inspection, authoring, failed preparation attempts, browsing, hashing and preflight compilation; not all interactive calls were metered. validation_commands.json records external builds separately. Package costs are in delivery/package_verification.json. No historical allowance/ledger used.')
write(D/'resource_accounting.json',resource)
text='# Focused robustness results — manuscript v9 / empirical v4\n\n'+table+'\n\n'
text+=f"Executed **{fit['actual_fits']} new fits**: 432 development and 360 final; **{fit['failed_fits']} failed fits**. All final stochastic blocks retain ten seeds. Executed neural updates: **{fit['executed_updates']:,}**; selected-checkpoint updates: **{fit['selected_updates']:,}**. Forty original final checkpoints were verified and reused; B2/B3 original fits and predictions remain separate, without new fitting.\n\n"
for s in ['source_excluded','primary_reanchored']:
 for c in ['ENsiRNA_grouped','APP','Davis_S7']:
  q=direct[(direct.scenario==s)&(direct.cohort==c)&(direct.b=='corrected_no_message')&(direct.weighting=='rows')].iloc[0];text+=f"- {s}, {c}: GNN minus matched no-message MSE **{q.difference:+.6f} [{q.lower:+.6f}, {q.upper:+.6f}]**, conditional on fixed ensembles and observed components.\n"
text+='\nBoth new S7 sensitivities establish a narrow conditional ensemble improvement over matched no-message; tree and CNN nevertheless have lower observed MSE. A general GNN advantage is not established by these heterogeneous sensitivities. Original APP tree–GNN differences are dominated by squared mean bias (99.53%). The original S7 routing improvement is a narrow conditional positive result; it does not establish a message-passing advantage. B2 sequence-specific measured chemistry prediction remains unestablished, and original B3 does not beat zero interaction. These are retrospective measured-data analyses, not independent external or new wet-lab validation.\n\n'
text+='Primary-source adjudication reproduces 299 residuals above .05 among 1,604 linked reported identities (max 1.0852170325). The 1,924 admitted Bramsen rows partition into 1,604 linked, 201 unmatched, 76 duplicate release mappings and 43 without a unique primary measurement. The separate primary-assay sensitivity contains 2,607 rows and preserves all released values; it is not a certified release repair. Full molecular/assay traceability remains incomplete. The primary article reports triplicate assays repeated twice, but shared-control covariance is unavailable. B2 replicate counts remain unresolved.\n\n'
text+='Exact input counts, chemistry-name support, all 140 cancellation flags, dependent leave-margin and reference-shift checks are in `visibility/`. Cross-campaign ranking uses identical 1,839 records and 17 pools; corrected exact tie handling retains the principal reversal. Earlier constants and some chemistry-invariant scores change under the common definition, and their originals are preserved. Published ENsiRNA/MEG exact reproductions remain blocked (zero fits); acquired Davis S1 remains quarantined.\n\n'
text+=f"Main pages **1–{bounds['main_end']}**; statements **{bounds['statements_start']}**; references **{bounds['references_start']}–{bounds['references_end']}**; appendix **{bounds['appendix_start']}–{bounds['appendix_end']} ({bounds['appendix_pages']} pages)**. The workflow is on page **{bounds['workflow_page']}**. Source validation, external build, independent ZIP build, proof preservation and all-page rendering are recorded separately.\n\n"
text+='Deliverables:\n\n- PDF: `papers/interaction_recoverability_iclr2027/v9/artifacts/main.pdf`\n- Four-entry source ZIP: `papers/interaction_recoverability_iclr2027/v9/artifacts/manuscript_source.zip`\n- External official dependencies: `papers/interaction_recoverability_iclr2027/v9/artifacts/typesetting_dependencies.zip`\n- Final referenced figures: `papers/interaction_recoverability_iclr2027/v9/source/figures/`\n- Full source adjudication: `'+str((RUN/'adjudication/row_reconciliation.csv').relative_to(ROOT))+'`\n- Predictions and checkpoint directories: `'+str((RUN/'evaluation').relative_to(ROOT))+'`, `'+str((RUN/'fits').relative_to(ROOT))+'`\n- Separate indexed evidence archive: `'+str((RUN/'delivery/robustness_code_results.zip').relative_to(ROOT))+'`\n\n'
text+=f"Recorded completed stage/diagnostic costs so far: {cpu:.3f} child CPU seconds and {wall:.3f} aggregate command wall seconds; max reported child RSS {rss/1024:.1f} MiB. GPU fitting-region elapsed {fit['gpu_region_wall_s']:.3f}s overlaps stage time and is not GPU kernel time or energy. Direct administrative work has additional unmetered nonzero cost; build/package receipts are separate. Historical datasets, proofs, predictions, configurations, checkpoints, logs and negative results remain preserved. No push, publishing or contact occurred.\n\n"
text+='The named handoff ZIP and review files were absent from the accessible workspace and attachments; the requested local path has not been supplied. The concrete review corrections in the root instruction were independently checked. This delivery does not claim extraction or inspection of missing files.\n'
(D/'execution_summary.md').write_text(text)
commands='# Executed commands and accounting\n\nThe scientific entry point was invoked as:\n\n```bash\nbash sirna_gnn_empirical/v4/run_all.sh adjudicate plan fit\n```\n\nEvery following child command is copied from its actual receipt, with exit status; a receipt is not a prepared command.\n\n'
for r in cmds:commands+='```bash\n'+r['command']+'\n```\n\n'+f"Exit {r['exit_code']}; wall {r['wall_s']:.3f}s; child CPU {r['child_cpu_s']:.3f}s; log `{r['log']}`.\n\n"
commands+='Additional executed direct preparation/authoring commands include `python sirna_gnn_empirical/v4/write_dataset.py`, script syntax checks, `prepare_minimal.py` (one-time initial source creation), iterative paper/build commands, rendering and source-ZIP checks. Their direct interactive costs are not all in the scientific stage receipt and are not assigned invented zero cost. Initial unsuccessful parsing/acquisition and ranking-member-count attempts are retained in the run attempt directories. Additional recorded typesetting attempts are verbatim in `authoring_commands.jsonl`; generation costs overlap the paper-stage receipts and are not summed twice. Final external build commands and their measured costs are verbatim in the manuscript artifacts `validation_commands.json`.\n\nThe default resumable entry point is `bash sirna_gnn_empirical/v4/run_all.sh`. It verifies completed stage hashes and skips them; this is distinct from executing a fresh fit. Do not delete completion records to reinterpret an old result as a new experiment. No historical allowance wrapper or ledger is used.\n'
(D/'executed_commands.md').write_text(commands)
# Every main object is mapped; numerical table values were generated from exact CSV rows.
main=(S/'main.tex').read_text();app=(S/'appendix.tex').read_text();objects=re.findall(r'\\label\{((?:fig|tab):[^}]+)\}',main);maprows=json.loads((RUN/'paper_tables/main_object_evidence.json').read_text());lookup={r['object']:r for r in maprows};figmap={'fig:workflow':('app:architecture; app:training','sirna_gnn_empirical/v4/architecture.py; original/new fit records; workflow_identity.json'),'fig:robustness':('app:focusedresults; app:metrics','v4/evaluation/activity_metrics.csv; v4/evaluation/seed_metrics.csv'),'fig:calibration':('app:robustness; app:metrics','v4/review_checks/calibration_decomposition.csv; v3/tables/direct_comparisons.csv'),'fig:visibility':('app:inputcollision; app:focusedresults','v4/visibility/input_counts.csv; v4/visibility/B3_rectangle_visibility.csv')}
audit='# Appendix completeness and main-claim mapping\n\nEvery complete historical finite-model proof is preserved verbatim; new exact input-cancellation and collision-floor proofs are complete. Calibration, endpoint derivatives, ensemble decomposition, metric and uncertainty definitions remain self-contained. Raw record dumps are replaced by compact complete summaries and exact evidence identifiers.\n\n| Main object | Complete appendix support | Exact numerical / implementation evidence |\n|---|---|---|\n'
for obj in objects:
 if obj in lookup:r=lookup[obj];support='A2–A6, A9–A10 as detailed in the appendix roadmap';ev='v4/'+r['table_csv']
 else:assert obj in figmap;support,ev=figmap[obj]
 audit+=f'| `{obj}` | {support} | `{ev}` |\n'
audit+='\nMain numerical prose dependencies:\n\n| Claim | Complete derivation / evidence |\n|---|---|\n| Source concentration and positive/negative per-source R² | `v4/review_checks/source_concentration.csv`, `source_scores.csv`; A9 denominator definitions |\n| 299/1,604 discrepancy, max 1.0852170325, 320 quarantines | `v4/adjudication/row_reconciliation.csv`, direct source cells and primary marginal checks; A9 |\n| Primary-assay eligibility and 2,607-row coverage | `v4/dataset/`, A9 complete target definition |\n| 792 new fits, ten seeds, 40 reused, updates | `v4/fit_summary.csv`, `fit_completion.json`, `evaluation/reused_fits.json`; A4/A9 |\n| APP gap and 99.53% squared-bias fraction | `v4/review_checks/calibration_decomposition.csv`; full A9 expansion |\n| Original S7 narrow improvement, no-message comparison | `v3/tables/direct_comparisons.csv`, `v4/review_checks/independent_conditional_comparisons.csv`; A5/A9 |\n| New conditional comparisons and seed variability | `v4/evaluation/direct_comparisons.csv`, `seed_stability.csv`, `seed_paired_differences.csv`; A5/A10 |\n| Ranking reversal and exact ties | `v4/ranking/` and `v4/evaluation/ranking_pools.csv`; A5/A9/A10 |\n| B2 means, sign controls, correlation and uncertainty limits | `v3/tables/pair_metrics.csv`, `pair_comparisons.csv`, `B2_within_assay_variation.csv`; A2/A4/A5/A7 |\n| B3 counts, nonzero predictions and cancellation | `v3/b3_primary/`, `v4/visibility/`; A6/A9/A10 complete proofs and dependence |\n| Published blockers/S1 | `v4/source_checks/`, original primary inputs and pinned source; A6 |\n| No new architecture, causal validation or five-law transfer | Exact A3 forward map and A9 scope; original theory preserved separately |\n'
audit+='\nActual boundary: '+json.dumps(bounds)+'. Zero undefined references and overfull boxes are required by the final build audit. All relevant original proof bodies pass byte-for-byte preservation; new proof bodies have no repository-only endpoint. The four-entry source and ZIP pass structural validation and a clean independent build.\n'
(D/'appendix_audit.md').write_text(audit);(D/'claim_audit.md').write_text(audit.replace('# Appendix completeness and main-claim mapping','# Scientific claim audit',1))
records=json.loads((RUN/'source_checks/citation_recheck.json').read_text());citation='# Citation audit\n\n43 unique bibliography entries were retained. Primary source evidence and scope were checked; no published asymptotic or expressivity theorem is imported as a GNN risk guarantee. Source-specific biological assertions retain assay and intervention restrictions. Official implementation claims refer to pinned code and actual unresolved blockers, not an inferred successful reproduction.\n\n| Key | Primary text | Permitted manuscript use |\n|---|---|---|\n'
for r in records:citation+=f"| `{r['key']}` | {r['primary_url']} | {r['current_claim']} |\n"
citation+='\nRetained primary bytes, checksums and relevant excerpts are in `v4/source_checks/citation_recheck.json`; source text is in `v3/sources/citations/`. The new source-specific adjudication separately rereads the primary Bramsen article, Table 1 and the exact supplement. The manuscript asserts its own elementary identities directly; it does not use a citation to hide an unverified model-specific proof.\n';(D/'citation_audit.md').write_text(citation)
print(table)
